name: Build and Publish Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Create package zip
        run: zip -r package.zip target

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v1.0.0  # Puoi specificare il numero di versione appropriato
          release_name: Release v1.0.0  # Puoi specificare il nome della release appropriato
          draft: false
          prerelease: false

      - name: Upload package zip
        uses: actions/upload-release-asset@v1
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package.zip
          asset_name: package.zip
          asset_content_type: application/zip
